version: '3.7'
services:
  contacts_api:
    image: contactsapi:v1
    ports:
      - "5002:80"
    depends_on:
      - mongo_db
    environment:
      - ASPNETCORE_ENVIRONMENT:'Development'
  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE:'ContactsDb'
